### ISSUE TITLE
img_cal of the normalized images is c(NaN,NaN)

### ISSUE THREAD

**Issue by Jfortin1** [muschellij2/WhiteStripe#1]
Here's my code to try to normalize the T1 scan from the package data:

download_img_data()
t1 = readNIfTI(system.file("T1Strip.nii.gz", package="WhiteStripe"))
ind <- whitestripe(t1,"T1")
t1.norm <- whitestripe_norm(t1, ind$mask)

> t1.norm@cal_max
> [1] Inf
> 
> t1.norm@cal_min
> [1] Inf
> 
> sum(is.na(t1.norm))
> [1] 6567232

Any hint why this is happening?

**Comment by muschellij2** [comment]
You are to pass the INDICES, not the mask.  I'll make it more robust so that if you pass in a nifti object, it assumes it's a mask and will take the indices.

```
> t1.norm <- whitestripe_norm(t1, ind$whitestripe.ind)
> cal.max(t1.norm)
[1] 23.69136
> cal.min(t1.norm)
[1] -163.5431
```

**Comment by Jfortin1** [comment]
Since the input object is a nifti object, it'd be more intuitive for the indices to be a nifti mask in my opinion. But thanks, it works now :)
