### ISSUE TITLE
the meaning of argument "type" in function "whitestripe"

### ISSUE THREAD

**Issue by FrankEP** [muschellij2/WhiteStripe#7]
Hi, thanks for your package. It's very helpful.
I want to ask the mean of T1, T2, FA, and MD, respectively. 
Is MD mean the T1-weighted modality after contrast agent injection while T1 means the modality before injection?
Is FA mean the FLAIR modality?
Looking forward to your reply.
Thanks very much.

**Comment by muschellij2** [comment]
T1 - T1-weighted Imaging
T2 - T2-weighted Imaging 
MD - mean diffusivity map from diffusion tensor imaging (DTI)
FA - fractional anisotrophy map from diffusion tensor imaging (DTI)

FLAIR is a T2 imaging modality, so if you want to perform this on FLAIR, use T2.

**Comment by FrankEP** [comment]
Got it! Thank you very much.
